---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkjapp
  labels:
    app: vkjapp
spec:
  selector:
    matchLabels:
      app: vkjapp
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/data/devwebapp/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret/data/devwebapp/config" -}}
          username={{ .Data.data.username }};password={{ .Data.data.password }}
          {{- end -}}
      labels:
        app: vkjapp
    spec:
      serviceAccountName: internal-app
      containers:
        - imagePullPolicy: "Always"
          name: vkjapp-java
          env:
          - name: SECRETS_LOCATION
            value: /vault/secrets/
          image: grenader/vault-kubernetes-java:v2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vkjapp
  name: vkjservice
spec:
  allocateLoadBalancerNodePorts: true
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: vkjapp
  type: LoadBalancer
