apiVersion: v1
kind: Service
metadata:
  name: vault-lb
spec:
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  type: LoadBalancer
